language: php
matrix:
    fast_finish: true
    include:
        - php: 7.1
        - php: 7.2
        - php: 7.3

cache:
    directories:
        - $HOME/.composer/cache

instal:
    - composer update --prefer-dist --no-interaction

script:
    - vendor/bin/phpunit
